<a href="https://colab.research.google.com/github/MishcaGestoso/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have?**

In [42]:
eq1 = np.array([[1,1,1],[1,0,4],[0,0,5]])
eq2 = np.array([[89],[89],[95]])
amt = np.linalg.inv(eq1).dot(eq2)
print(amt)

[[13.]
 [57.]
 [19.]]


**Problem 2. Solve each system:** 

**3x - y + z = 5**

**9x - 3y +3z = 15**

**-12x +4y -4z = -20** 

In [43]:
import numpy as np
#from scipy.linalg import solve

A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print (A)

inv_A = np.linalg.inv(A)
print(inv_A)


[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]


LinAlgError: ignored

##Explanation
 The code results to error because there is an incompatibility of three linear equations, which will result in LinearAlgError, there is only a single matrix.

**Problem 3. find the  eigenvalue/s and the eigenvectors**

In [39]:
import numpy as np
from numpy.linalg import eig
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]]) #this is the Matrix A
print("Matrix A\n", A)
print("\n")

w,v = np.linalg.eig(A)
print("The eigenvalues is/are:\n",w)
print("\n")
print("The eigenvectors are:\n",v)
print("\n")

x = v.round()
print("Round:\n",x)


Matrix A
 [[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]


The eigenvalues is/are:
 [-1.  3.  2.]


The eigenvectors are:
 [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]


Round:
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
