<a href="https://colab.research.google.com/github/MishcaGestoso/Linear-Algebra-58019/blob/main/Linear_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To find the inverse of the matrix, the matrix is passed to the linalg.inv() of the NumPy module:




In [30]:
import numpy as np
A = np.array([[4,3],[-5,9]]) #creation of matrix A
print (A)
inv_A= np.linalg.inv(A)
print (inv_A)

[[ 4  3]
 [-5  9]]
[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


In [31]:
B = np.array([[20],[26]])
print(B)

[[20]
 [26]]


In [32]:
X = np.linalg.inv(A).dot(B)
print(X)

[[2.]
 [4.]]


In [33]:
X = np.dot(inv_A,B)
print(X)

[[2.]
 [4.]]


Solution for the given Linear Equations:


In [34]:
import numpy as np
A = np.array([[[4,3,2],[-2,2,3],[3,-5,2]]])
print(A)
inv_A=np.linalg.inv(A)
print(inv_A)


[[[ 4  3  2]
  [-2  2  3]
  [ 3 -5  2]]]
[[[ 0.15447154 -0.1300813   0.04065041]
  [ 0.10569106  0.01626016 -0.1300813 ]
  [ 0.03252033  0.23577236  0.11382114]]]


In [35]:
B = np.array([[[25],[-10],[-4]]])
print(B)

[[[ 25]
  [-10]
  [ -4]]]


In [36]:
X = np.linalg.inv(A).dot(B)
print(X)

[[[[ 5.]]

  [[ 3.]]

  [[-2.]]]]


Application

In [37]:
A = np.array([[20,10],[17,22]]) #creation of Matrix A
print(A)
inv_A = np.linalg.inv(A)
print(inv_A)

[[20 10]
 [17 22]]
[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]


In [38]:
B = np.array([[350],[500]]) #creation of Matrix B
print(B)

[[350]
 [500]]


In [39]:
X = np.dot(inv_A,B)
print(X)

[[10.]
 [15.]]


To check if the answer is correct:

In [40]:
B = np.dot(A,X)
print(B)

[[350.]
 [500.]]
