<a href="https://colab.research.google.com/github/MishcaGestoso/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1. Create a Python code that displays a square matrix whose length is 5 

In [21]:
import numpy as np #import Library
#A square matrix has the same length and breadth, it is a 5x5 matrix.

SquareMatrix = np.array ([[1,2,3,4,5],[2,0,0,0,0],[3,0,0,0,0],[4,0,0,0,0],[5,0,0,0,0]]) #5x5 matrix

print("This is an example of square matrix whose length is 5")
print() #this is for spacing and also optional
print(SquareMatrix) 

This is an example of square matrix whose length is 5

[[1 2 3 4 5]
 [2 0 0 0 0]
 [3 0 0 0 0]
 [4 0 0 0 0]
 [5 0 0 0 0]]


Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero

In [19]:
import numpy as np
C = np.triu([[1,2,3],[2,4,6],[3,6,9,]])
print(C)

[[1 2 3]
 [0 4 6]
 [0 0 9]]


Question 3. Create a Python code that displays a square matrix which is symmetrical 

In [25]:
import numpy as np
square_matrix = np.array([[1,2,3,4,5],[2,1,2,3,4],[3,2,1,2,3],[4,3,2,1,2],[5,4,3,2,1]]) #Creation of a 5x5 matrix named as square matrix
print('A square matrix which is symmetrical: ') #Text message indicating the result
print(square_matrix) #Displays the final output

A square matrix which is symmetrical: 
[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


Question 4. What is the inverse of matrix C? Show your solution by python coding.  

In [10]:
import numpy as np
C = np.array ([[1,2,3],[2,3,3],[3,4,-2]]) #The matrix of C

invC = np.linalg.inv(C)

print("Inverse of Matrix C:")
print(invC) #print the inverse of C

Inverse of Matrix C:
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. 

In [14]:
import numpy as np
C = np.array ([[1,2,3],[2,3,3],[3,4,-2]])

detOfC = np.linalg.det(C)

print("The determinant of the given matrix in Question 4:")
print(int(detOfC)) #print the determinant of C

The determinant of the given matrix in Question 4:
5



Question 6. Find the roots of the linear equations by showing its python codes

In [12]:
import numpy as np
eq = np.array([[5,4,1],[10,9,4],[10,13,15]])

const = np.array([[[3.4],[8.8],[19.2]]])

roots = np.linalg.inv(eq) @ const

print("Roots of the given linear equations:")
print(roots)

Roots of the given linear equations:
[[[0.2]
  [0.4]
  [0.8]]]
