<a href="https://colab.research.google.com/github/MishcaGestoso/Linear-Algebra-58019/blob/main/Practical_Lab_Exam1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Practical Lab Exam 1

##Problem 1

In [35]:
import numpy as np
A = np.array ([[1,2,3],[4,5,6]]) #This is matrix A
print("\nA")
print(A)

B = np.array ([[1,2],[3,4],[5,6]]) #This is matrix B
print("\nB")
print(B)

C = np.array ([[1,2,3],[4,5,6],[7,8,9]]) #This is matrix C
print("\nC")
print(C)

D = np.array ([[1,2],[3,4]]) #This is matrix D
print("\nD")
print(D)


A
[[1 2 3]
 [4 5 6]]

B
[[1 2]
 [3 4]
 [5 6]]

C
[[1 2 3]
 [4 5 6]
 [7 8 9]]

D
[[1 2]
 [3 4]]


##A. AB

In [16]:
import numpy as np
A = np.array ([[1,2,3],[4,5,6]])
B = np.array ([[1,2],[3,4],[5,6]])
dot = np.dot(A,B)
print(dot)

[[22 28]
 [49 64]]


##B. D +  D

In [17]:
import numpy as np
D = np.array ([[1,2],[3,4]])
print(D+D)

[[2 4]
 [6 8]]


##C. 2C

In [18]:
import numpy as np
C = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(2*C)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


##Problem 2

In [36]:
import numpy as np
X = np.array([5,3,-1])

print(X)
print('\nType of array:', type(X))    #array
print('Size of array:', X.size)       #size
print('Shape of array:', X.shape)     #shape
print('Dimension of array:', X.ndim)  #dimension


[ 5  3 -1]

Type of array: <class 'numpy.ndarray'>
Size of array: 3
Shape of array: (3,)
Dimension of array: 1
