<a href="https://colab.research.google.com/github/MishcaGestoso/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Prelim Exam

Question 1.
A 4 x 4 matrix whose diagonal elements are all one (1's)

In [6]:
import numpy as np
A = np.array([1,1,1,1,])
C = np.diag(A)
print (C)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


Question 2. doubles all the values of each element.

In [11]:
import numpy as np
A = np.array([1, 1, 1, 1])
B = np.diag(A)
print (C*2) #To double the value of array C


[[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 2]]


Question 3. The cross-product of matrices, A = [2,7,4] and B = [3,9,8]



In [12]:
import numpy as np
A = np.array([2, 7, 4])
B = np.array([3, 9, 8])
#To compute the cross of arrays A and B
cross = np.cross(A,B)
print(cross)

[20 -4 -3]
