<a href="https://colab.research.google.com/github/MishcaGestoso/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix and Its Operations

In [8]:
import numpy as np
A = np.array([[-5,0],[4,1]]) #This is matrix A
print(a)
B = np.array([[6,-3],[2,3]]) #This is matrix B
print(b)

[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]


In [7]:
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(A+B)


[[ 1 -3]
 [ 6  4]]


In [13]:
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(B-A)


[[11 -3]
 [-2  2]]


In [12]:
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(A-B)

[[-11   3]
 [  2  -2]]
