<a href="https://colab.research.google.com/github/MishcaGestoso/Linear-Algebra-58019/blob/main/Python_Exercise2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Vector Space Operations**

Representing Vectors


In [1]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])
print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


##Describing Vectors in NumPy

In [5]:
import numpy as np
ball1 =np.array([1,2,3])
ball2 =np.array([0,1,-1])
pool  =np.array([ball1,ball2])
pool.shape
pool.ndim

2

In [7]:
u = np.array([[1,2,3],[4,5,6]])
u.shape

(2, 3)

In [8]:
u = np.array([[1,2,3],[4,5,6]])
u

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
u = np.array([[1,2,3],[4,5,6]])
u
u.size

6

In [12]:
u = np.array([[1,2,3],[4,5,6]])
u.ndim

2

#Spaces


##Vector spaces are mathematical objects that abstractly capture the geometry and algebra of linear equations.

Addition of vectors

In [13]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
sum

array([1, 1, 0])

In [18]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
resultant = np.add(addend1, addend2)
resultant

array([1, 1, 0])

###Substraction of Vector

In [23]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
Difference = addend2 - addend1
Difference

array([1, 1, 0])

In [27]:
difference2 = np.subtract(addend1,addend2)
difference2

array([-1, -1,  0])

Scaling

In [31]:
A = np.array([1,5,8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

Cross product

In [32]:
A = np.array([2,3])
B = np.array([1,7])

#compute the cross product of A and B
cross = np.cross(A,B)
print(cross)

11


In [33]:
A = np.array([2,3,4])
B = np.array([1,7,1])

#compute the cross product of A and B
cross = np.cross(A,B)
print(cross)

[-25   2  11]
